# .github/workflows/gh_pages_deploy.yml

name: Build and Test
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using
        # npm and outputs the result to the 'build' folder. Replace with
        # the commands required to build your project, or remove this step
        # entirely if your site is pre-built.
        run: |
          npm install
          npm run lint
          npm run build
          npm run test
